name: Create Dokka Documentation after release

on: push

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: dokka
    - name: copy file via ssh password
    - uses: appleboy/scp-action@master
        with:
          host: emig.me
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          source: "/var/www/vhosts/emig.me/httpdocs/doc"
          target: "dokka"