name: Create Dokka Documentation after release

on: push

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: dokka
    - run: |
        ls -a
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v1
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "/dokka"
        remoteDir: ""      
    
