name: jvmBuild

on: push

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: jvmMainClasses